server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authorization
    password:
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          issuer-uri: http://localhost:9000
  flyway:
    baseline-on-migrate: true
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: trace
    org.springframework.security.jackson2: INFO

